# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
  - id: 84532
    start_block: 0
    contracts:
      - name: ShieldedPool
        address:
          - 0x55A51948F10924428C9D7A9916244A613abD3Ae0
        handler: src/EventHandlers.ts
        events:
          - event: Deposited(bytes32 indexed commitment, uint256 indexed leafIndex, bytes32 indexed root, uint256 amount)
          - event: Spent(bytes32 indexed nullifier, bytes32 indexed merchantCommitment, bytes32 indexed changeCommitment, uint256 amount, bytes32 challengeHash, uint256 merchantLeafIndex, uint256 changeLeafIndex, bytes32 newRoot)
          - event: Withdrawn(address indexed merchant, address indexed recipient, uint256 amount, bytes32 indexed claimId)
unordered_multichain_mode: true
preload_handlers: true
